# Generated by Django 5.1 on 2024-08-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_tag_remove_article_sector_article_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
