# Generated by Django 4.2.15 on 2024-08-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_sector_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('buyhold_profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('profit_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyhold_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('return_p', models.DecimalField(decimal_places=4, max_digits=6)),
                ('return_bh', models.DecimalField(decimal_places=4, max_digits=6)),
                ('return_daily', models.DecimalField(decimal_places=4, max_digits=6)),
                ('return_bh_daily', models.DecimalField(decimal_places=4, max_digits=6)),
                ('alpha', models.DecimalField(decimal_places=4, max_digits=6)),
                ('beta', models.DecimalField(decimal_places=4, max_digits=6)),
                ('sharpe_ratio', models.DecimalField(decimal_places=4, max_digits=6)),
                ('sortino_ratio', models.DecimalField(decimal_places=4, max_digits=6)),
                ('in_market_days', models.IntegerField()),
                ('total_days', models.IntegerField()),
            ],
        ),
    ]
