# Generated by Django 4.2.15 on 2024-08-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_tradingresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingresult',
            name='backtest_plot',
            field=models.ImageField(blank=True, null=True, upload_to='backtest_plots/'),
        ),
    ]
