# Generated by Django 4.2.15 on 2024-08-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_tradingresult_backtest_plot'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingresult',
            name='name',
            field=models.CharField(default='EquityGuardian', max_length=100),
        ),
    ]
